extends: semantic-release-monorepo
branches: release/*
plugins:
  - '@semantic-release/commit-analyzer'
  - - semantic-release-lerna
    - generateNotes: true
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - lerna.json
        - nx.json
        - pnpm-lock.yaml
        - pnpm-workspace.yaml
        - packages/*/package.json
        - pacages/*/pnpm-lock.yaml
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
