name: Test Coverage full
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [20, 21] #lts, latest
        pnpm-version: [8.11.0, 8.10.5] # current, stable

    steps:
      - name: setup nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: setup pnpm ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v2
        with:
          version: ${{matrix.pnpm-version}}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install
        continue-on-error: false

      - name: Run tests
        run: pnpm run test
        continue-on-error: false

      - name: Run test coverage
        run: pnpm run test:cov
        continue-on-error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.}}
          flags: unit test
          name: Codecov Report
          verbose: true
          fail_ci_error: true
